"""initial models

Revision ID: 072263609b1a
Revises: 
Create Date: 2026-07-11 14:46:07.139499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072263609b1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('github_event_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('repo_name', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_event_id')
    )
    with op.batch_alter_table('cached_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cached_event_username'), ['username'], unique=False)

    op.create_table('cached_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('profile_json', sa.JSON(), nullable=True),
    sa.Column('repos_json', sa.JSON(), nullable=True),
    sa.Column('languages_json', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cached_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cached_summary_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cached_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cached_summary_username'))

    op.drop_table('cached_summary')
    with op.batch_alter_table('cached_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cached_event_username'))

    op.drop_table('cached_event')
    # ### end Alembic commands ###
