"""add github_created_at to cached_event

Revision ID: af536224d585
Revises: 072263609b1a
Create Date: 2026-07-13 18:37:27.017163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af536224d585'
down_revision = '072263609b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cached_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cached_event', schema=None) as batch_op:
        batch_op.drop_column('github_created_at')

    # ### end Alembic commands ###
